
services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: my_postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  upstream_app:
    image: alpine:latest
    container_name: my_upstream_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpassword
      # Hier können zusaetzliche Umgebungsvariablen hinzugefuegt werden, falls erforderlich
      CUSTOM_ENV_VAR1: value1
      CUSTOM_ENV_VAR2: value2
    command: sh -c "env && echo World && sleep 3000"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: